### ISSUE TITLE
Some errors were reported during loading

### ISSUE THREAD

**Issue by ming-589** [oanegros/tif2blender#48]
The node named "Material Output" is not created before it is used.
Thanks！

Python: Traceback (most recent call last):
  File "C:\Users\Youming Xiao\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\tif2blender\ui\ui.py", line 75, in execute
    load.load()
  File "C:\Users\Youming Xiao\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\tif2blender\load.py", line 117, in load
    vol_obj, volume_inputs = load_volume(volume_inputs, bbox_px, scale, cache_coll, base_coll, emission)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Youming Xiao\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\tif2blender\load_components\load_volume.py", line 142, in load_volume
    materials = volume_materials(volume_inputs, emission_setting) 
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Youming Xiao\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\tif2blender\load_components\load_volume.py", line 106, in volume_materials
    nodes.get("Material Output").location = (700,00)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'location'
![c22dc398776f35af4c2ba55aa85c1f3](https://github.com/oanegros/tif2blender/assets/127096977/2a482c1b-432c-4f7c-a493-5ed627a4988f)

**Comment by oanegros** [comment]
Okay, good to know! I haven't seen this before, where the materials don't auto-generate the Material Output. 
So it might be a more complicated issue that i do not yet understand, but this may also work:
[tif2blender_1.0.1.zip](https://github.com/user-attachments/files/15912141/tif2blender_1.0.1.zip)

Could you install this version and see if it works (to be sure, you can remove the current version, restart Blender, and then install this version)

**Comment by ming-589** [comment]
I'm glad you got back to me so quickly. I updated the script version, the problem is better, but there seems to be a new error.

Python: Traceback (most recent call last):
  File "C:\Users\Youming Xiao\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\tif2blender\ui\ui.py", line 75, in execute
    load.load()
  File "C:\Users\Youming Xiao\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\tif2blender\load.py", line 117, in load
    vol_obj, volume_inputs = load_volume(volume_inputs, bbox_px, scale, cache_coll, base_coll, emission)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Youming Xiao\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\tif2blender\load_components\load_volume.py", line 151, in load_volume
    mat.node_tree.nodes["Emission"].inputs[0].show_expanded = True
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Emission" not found'
![屏幕截图 2024-06-20 183505](https://github.com/oanegros/tif2blender/assets/127096977/5ae220c3-8f21-4e37-8f24-703ccad6976e)

**Comment by oanegros** [comment]
[tif2blender_1.0.1.zip](https://github.com/user-attachments/files/15912851/tif2blender_1.0.1.zip)
okay your screenshot also showed me that something else was accidentally going wrong, thanks! Please let me know if this one works now, but use the 'Force remaking vdb files option' for the first load.

**Comment by oanegros** [comment]
And which operating system (windows, linux, mac) do you run on?

**Comment by ming-589** [comment]
Windows10

**Comment by ming-589** [comment]
I reloaded it and it's working fine. Thank you very much for your help.

**Comment by oanegros** [comment]
Great! Thanks so much for trying new versions so quickly!
